sudo: required
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-contributions@amazon.com
      - travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  global:
    - GITHUB_ACCOUNT=aws-robotics
    - PACKAGE_NAME=tts
    - LANG=python
    - ROS_DISTRO=kinetic ROS_VERSION=1
    - ROS_DISTRO=lunar   ROS_VERSION=1
    - ROS_DISTRO=melodic ROS_VERSION=1
install:
  - git clone https://github.com/juanrh/travis-scripts.git .ros_ci
script:
  - .ros_ci/travis.sh
